export const env = {
  USER_AGENT: process.env.NEXT_PUBLIC_USER_AGENT as string,
  ACCESS_TOKEN: process.env.NEXT_PUBLIC_ACCESS_TOKEN,
  CONTENTFUL_SPACE_ID: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
  CONTENTFUL_MANAGEMENT_TOKEN: process.env.CONTENTFUL_MANAGEMENT_TOKEN,
  CONTENTFUL_DELIVERY_ACCESS_TOKEN: process.env.CONTENTFUL_DELIVERY_ACCESS_TOKEN,
}